# Generated by Django 3.2.7 on 2021-10-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_album', models.ImageField(blank=True, null=True, upload_to='albums_images')),
                ('song_name', models.CharField(blank=True, max_length=256, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=256, null=True)),
                ('music_file', models.FileField(blank=True, null=True, upload_to='music_file')),
                ('size_music', models.CharField(blank=True, max_length=64, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songsapp.contentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя блога')),
                ('image_blog', models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='Фото блога')),
                ('blog_desription', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание блога')),
                ('blog_duration', models.CharField(blank=True, max_length=32, null=True, verbose_name='Продолжительность')),
                ('blog_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Тип блога')),
                ('blog_date', models.CharField(blank=True, max_length=32, null=True, verbose_name='Дата блога')),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='Ссылка видео')),
                ('in_one_image', models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='Первое фото внутри')),
                ('in_two_image', models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='Второе фото внутри')),
                ('in_paragraph_one', models.CharField(blank=True, max_length=256, null=True, verbose_name='Первый заголовок')),
                ('in_paragraph_two', models.TextField(blank=True, null=True, verbose_name='Первое описание')),
                ('in_paragraph_three', models.CharField(blank=True, max_length=256, null=True, verbose_name='Второй заголовок')),
                ('in_paragraph_four', models.TextField(blank=True, null=True, verbose_name='Второе описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songsapp.contentcategory')),
            ],
        ),
    ]
