# Generated by Django 3.2.7 on 2021-10-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url_video',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка видео'),
        ),
    ]
